---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.lvm.storageClassStub }}-linear
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
provisioner: {{ .Values.lvm.driverName }}
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "linear"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.lvm.storageClassStub }}-mirror
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
provisioner: {{ .Values.lvm.driverName }}
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: mirror
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.lvm.storageClassStub }}-striped
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
provisioner: {{ .Values.lvm.driverName }}
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "striped"
