name: Publish

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Publish
      uses: Gerrit91/helm-gh-pages@override-releases
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        linting: off
